# Generated by Django 4.1.2 on 2022-10-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snmae', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
