# Generated by Django 4.1.2 on 2022-10-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='snmae',
            new_name='sname',
        ),
    ]
